name: .NET Build

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Obfuscation.Tasks project dependencies
      run: dotnet restore src/Obfuscation.Tasks/Obfuscation.Tasks.csproj
    - name: Build Obfuscation.Tasks project
      run: dotnet build src/Obfuscation.Tasks/Obfuscation.Tasks.csproj --no-restore --configuration Release
    - name: Pack Obfuscation.Tasks project
      run: dotnet pack src/Obfuscation.Tasks/Obfuscation.Tasks.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
    - name: Test
      run: dotnet test --no-build --verbosity normal
